version: '2'
services:
  pets:
    container_name: pets-container
    image: darteaga/pets
    links:
      - mongodb
    environment:
      - HOST=localhost
      - SERVER_PORT=4000
      - MONGO_URL=mongodb://mongodb:27017/pets
    ports:
      - 4000:4000
    restart: always
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb-container
    image: bitnami/mongodb:4.2-debian-9
    ports:
      - 27017:27017
    #    volumes:
    #      - ./data:/data/db

    restart: always
