version: '2'
services:
  pets:
    container_name: pets-container
    build: .
    image: darteaga/pets
    links:
      - mongodb
    environment:
      - SERVER_HOSTNAME=localhost
      - SERVER_PORT=4000
      - MONGO_URL=mongodb://mongodb:27017/pets
    ports:
      - 4000:4000
    restart: always
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb-container
    image: bitnami/mongodb:4.2-debian-9
    volumes:
      - mongo_data:/data/db

    restart: always

volumes:
  mongo_data:
