version: '2'
services:

  pets:
    container_name: pets-container
    image: darteaga/pets
    links:
      - mongodb
    environment:
      - NODE_ENV=production
    ports:
      - 80:80
    restart: always

  mongodb:
    container_name: mongodb-container
    image: mongo
    ports:
      - 27017:27017
    restart: always
