version: 2.1

references:
  js_deps_cache_key: &js_deps_cache_key v1-dependency-{{ checksum "package-lock.json" }}

master_only: &master_only
  filters:
    branches:
      only: master

commands:
  git_authoring:
    description: Authoring git commit.
    steps:
      - run: git config --global push.default matching
      - run: git config --global user.email "totem-bot@darteaga.com"
      - run: git config --global user.name "Totem Bot"

jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - *js_deps_cache_key
      - run:
          name: Install dependencies.
          command: npm i
      - save_cache:
          paths:
            - node_modules
          key: *js_deps_cache_key

  test:
    docker:
      - image: circleci/node:12
      - image: bitnami/mongodb:4.2-debian-9
    environment:
      NODE_ENV: ci
    steps:
      - checkout
      - restore_cache:
          keys:
            - *js_deps_cache_key
      - run:
          name: Execute unit tests.
          command: npm test

  # release:
  #   docker:
  #     - image: circleci/node:12
  #   steps:
  #     - checkout
  #     - git_authoring
  #     - restore_cache:
  #         keys:
  #           - *js_deps_cache_key
  #     - run:
  #         name: Bump and publish the new version.
  #         command: npm run release

  publish:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - *js_deps_cache_key
      - run:
          name: Docker login
          command: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: Build docker image.
          command: docker build -t darteaga/pets:$CIRCLE_BRANCH .
      - run:
          name: Publish to public dockerhub.
          command: docker push darteaga/pets:$CIRCLE_BRANCH

workflows:
  version: 2
  default:
    jobs:
      - build
      - test:
          requires:
            - build
      # - release:
      #     <<: *master_only
      #     requires:
      #       - test
      - publish:
          <<: *master_only
          requires:
            - test
