version: 2.1

references:
  js_deps_cache_key: &js_deps_cache_key v1-dependency-{{ checksum "package-lock.json" }}

master_only: &master_only
  filters:
    branches:
      only: master

commands:
  git_authoring:
    description: Authoring git commit.
    steps:
      - run: git config --global push.default matching
      - run: git config --global user.email "totem-bot@darteaga.com"
      - run: git config --global user.name "Totem Bot"

jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - *js_deps_cache_key
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: *js_deps_cache_key

  test:
    docker:
      - image: circleci/node:12
      - image: bitnami/mongodb:4.2-debian-9
    environment:
      NODE_ENV: ci
    steps:
      - checkout
      - restore_cache:
          keys:
            - *js_deps_cache_key
      - run: npm test

  release:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - git_authoring
      - restore_cache:
          keys:
            - *js_deps_cache_key
      - run: npm run release

  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: git pull  # get all the changes before release step changes.
      - setup_remote_docker
      - restore_cache:
          keys:
            - *js_deps_cache_key
      - run: echo 'export MAIN_TAG="$(npm run --silent get:version)"' >> $BASH_ENV
      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: docker build -t darteaga/pets:$MAIN_TAG .
      - run: docker push darteaga/pets:$MAIN_TAG
      - run: docker tag darteaga/pets:$MAIN_TAG darteaga/pets:latest
      - run: docker push darteaga/pets:latest


workflows:
  version: 2
  default:
    jobs:
      - build
      - test:
          requires:
            - build
      - release:
          <<: *master_only
          requires:
            - test
      - deploy:
          <<: *master_only
          requires:
            - release
