---
development:
  initialData: 'true'
  port: 5000
  db:
    mongoUrl: mongodb://localhost/pets

production:
  initialData: false
  port: 80
  db:
    mongoUrl: mongodb://mongodb/pets

test:
  initialData: 'true'
  port: 5000
  db:
    mongoUrl: mongodb://localhost/pets